# Generated by Django 4.2.2 on 2023-07-07 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SongSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=512, verbose_name="Ссылка")),
                ("service", models.CharField(max_length=128, verbose_name="Сервис")),
                ("is_audio_only", models.BooleanField(verbose_name="Только аудио")),
            ],
            options={
                "verbose_name": "Источник песни",
                "verbose_name_plural": "Источники песен",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "artist",
                    models.CharField(max_length=128, verbose_name="Исполнитель"),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.songsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Песня",
                "verbose_name_plural": "Песни",
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("isPublic", models.BooleanField(verbose_name="Публичный")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("songs", models.ManyToManyField(to="music.song")),
            ],
            options={
                "verbose_name": "Плейлист",
                "verbose_name_plural": "Плейлисты",
            },
        ),
        migrations.CreateModel(
            name="MusicSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("songs", models.ManyToManyField(to="music.song")),
            ],
            options={
                "verbose_name": "Музыкальный источник",
                "verbose_name_plural": "Музыкальные источники",
            },
        ),
    ]
