# Generated by Django 4.2.2 on 2023-07-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_songlistendate_song_musicsourcedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicsource",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="source",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music.songsource",
            ),
        ),
    ]
