# Generated by Django 4.2.2 on 2023-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_alter_musicsource_name_alter_song_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicsource",
            name="songs",
            field=models.ManyToManyField(related_name="sources", to="music.song"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(related_name="playlists", to="music.song"),
        ),
    ]
