# Generated by Django 4.2.2 on 2023-07-24 08:27

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                (
                    "stream_url",
                    models.CharField(max_length=512, verbose_name="Ссылка на поток"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=music.models.radio_logo,
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Радио",
                "verbose_name_plural": "Радио",
            },
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="json",
            field=models.TextField(verbose_name="Настройки в формате JSON"),
        ),
    ]
