# Generated by Django 4.2.2 on 2023-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_radio_alter_usersettings_json"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"verbose_name": "Песня", "verbose_name_plural": "Песни"},
        ),
        migrations.AlterField(
            model_name="songsource",
            name="url",
            field=models.CharField(max_length=512, verbose_name="Ссылка"),
        ),
    ]
