# Generated by Django 4.2.7 on 2024-01-17 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "author_title",
                    models.CharField(max_length=64, verbose_name="Подпись автора"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата написания"
                    ),
                ),
                (
                    "edited",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "is_edit_public",
                    models.BooleanField(
                        default=True, verbose_name="Публичное редактирование"
                    ),
                ),
                (
                    "is_view_public",
                    models.BooleanField(
                        default=True, verbose_name="Публичный просмотр"
                    ),
                ),
                ("text", models.TextField(default="", verbose_name="Исходный текст")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
