# Generated by Django 4.2.2 on 2023-07-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_post_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.avatar_file,
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.TextField(blank=True, null=True, verbose_name="Статус"),
        ),
    ]
